/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-02-20 02:05:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.GiaoDien.auth;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\" />\r\n");
      out.write("		<title>Form đăng ký thành viên VinaEnter Edu</title>\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/auth/styles_signup.css\" />\r\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css?family=Roboto\" rel=\"stylesheet\" />\r\n");
      out.write("		<script src=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/auth/js/jquery-3.2.1.js\"></script>\r\n");
      out.write("		<script src=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/auth/js/jquery.validate.min.js\"></script>		\r\n");
      out.write("		<script src=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/auth/js/validate_sign.js\"></script>		\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("	\r\n");
      out.write("		<form class=\"form\" action=\"\" method=\"post\">\r\n");
      out.write("			<h2>ĐĂNG KÝ THÀNH VIÊN TRANG BSONG VINAENTER EDU</h2>	\r\n");
      out.write("			");

			String error = request.getParameter("error");
			if("1".equals(error)){
				out.print("<p style=\"color: red; \">Đăng ký thành viên không thành công, tên đăng ký trùng.</p>");
			}
			String name = request.getParameter("username");
			String fullname = request.getParameter("fullname");
			
			
      out.write("\r\n");
      out.write("			<p>\r\n");
      out.write("				<label>Tên truy cập (*):</label>\r\n");
      out.write("				<input name=\"username\" value=\"");
if(name != null) out.print(name); 
      out.write("\" type=\"text\" placeholder=\"Choose your username\" />\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<label>Mật khẩu (*):</label>\r\n");
      out.write("				<input name=\"password\" value=\"\" id=\"password\" type=\"password\" placeholder=\"Creat a new password\" />\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<label>Xác nhận mật khẩu (*):</label>\r\n");
      out.write("				<input name=\"repassword\" value=\"\" type=\"password\" placeholder=\"Confirm your password\" />\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<label>Họ và tên (*):</label>\r\n");
      out.write("				<input name=\"fullname\" value=\"");
if(fullname != null) out.print(fullname); 
      out.write("\" type=\"text\" placeholder=\"Write your name here..\" />\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<input type=\"submit\" name=\"submit\" value=\"ĐĂNG KÝ\"/>\r\n");
      out.write("				<input type=\"reset\" name=\"reset\" value=\"RESET\" />\r\n");
      out.write("				<a href=\"");
      out.print(request.getContextPath());
      out.write("/login\"><input type=\"button\" name=\"login\" value=\"LOGIN\" /></a>				\r\n");
      out.write("			</p>\r\n");
      out.write("			<div class=\"contact\">\r\n");
      out.write("				<span class=\"fa fa-phone\"></span>0905.051.720\r\n");
      out.write("				<span class=\"fa fa-envelope-o\"></span>info@vinaenter.edu.vn\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
