/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-02-20 15:30:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.GiaoDien.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import util.DefineUtil;
import model.dao.CatergoriesDAO;
import model.bean.Categories;
import model.bean.Songs;
import java.util.ArrayList;
import model.bean.Users;

public final class indexSong_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/GiaoDien/admin/inc/leftbar.jsp", Long.valueOf(1676452649343L));
    _jspx_dependants.put("/GiaoDien/admin/inc/header.jsp", Long.valueOf(1676299642896L));
    _jspx_dependants.put("/GiaoDien/admin/inc/footer.jsp", Long.valueOf(1676032827784L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.bean.Users");
    _jspx_imports_classes.add("model.bean.Categories");
    _jspx_imports_classes.add("model.bean.Songs");
    _jspx_imports_classes.add("util.DefineUtil");
    _jspx_imports_classes.add("model.dao.CatergoriesDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>AdminCP | VinaEnter Edu</title>\r\n");
      out.write("    <!-- BOOTSTRAP STYLES-->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/admin/assets/css/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- FONTAWESOME STYLES-->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/admin/assets/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- CUSTOM STYLES-->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/admin/assets/css/custom.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- GOOGLE FONTS-->\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        <nav class=\"navbar navbar-default navbar-cls-top \" role=\"navigation\" style=\"margin-bottom: 0\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".sidebar-collapse\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("/admin/trang-chu\">VinaEnter Edu</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

            	Users userLogin = (Users) session.getAttribute("userLogin");
            	if(userLogin != null){
            
      out.write("<div style=\"color: white;padding: 15px 50px 5px 50px;float: right;font-size: 16px;\"> Xin chào, <b>");
      out.print(userLogin.getFullname());
      out.write("</b> &nbsp; <a href=\"");
      out.print(request.getContextPath());
      out.write("/logout\" class=\"btn btn-danger square-btn-adjust\">Đăng xuất</a> </div>\r\n");
      out.write("       		");
}else { 
      out.write("<div style=\"color: white;padding: 15px 50px 5px 50px;float: right;font-size: 16px;\"> Xin chào, <b>khách</b> &nbsp; <a href=\"");
      out.print(request.getContextPath());
      out.write("/login\" class=\"btn btn-danger square-btn-adjust\">Đăng nhập</a> </div>\r\n");
      out.write("       		");
} 
      out.write("</nav>\r\n");
      out.write("        <!-- /. NAV TOP  -->");
      out.write("<nav class=\"navbar-default navbar-side\" role=\"navigation\">\r\n");
      out.write("    <div class=\"sidebar-collapse\">\r\n");
      out.write("        <ul class=\"nav\" id=\"main-menu\">\r\n");
      out.write("            <li class=\"text-center\">\r\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/admin/assets/img/find_user.png\" class=\"user-image img-responsive\" />\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a id=\"index\" href=\"");
      out.print(request.getContextPath());
      out.write("/admin/trang-chu\"><i class=\"fa fa-dashboard fa-3x\"></i> Trang chủ</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a id=\"category\" href=\"");
      out.print(request.getContextPath());
      out.write("/admin/cats\"><i class=\"fa fa-list fa-3x\"></i> Quản lý danh mục</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a id=\"song\" href=\"");
      out.print(request.getContextPath());
      out.write("/admin/songs\"><i class=\"fa fa-music fa-3x\"></i> Quản lý bài hát</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a id=\"user\" href=\"");
      out.print(request.getContextPath());
      out.write("/admin/users\"><i class=\"fa fa-user fa-3x\"></i> Quản lý người dùng</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a id=\"contact\" href=\"");
      out.print(request.getContextPath());
      out.write("/admin/contacts\"><i class=\"fa fa-envelope fa-3x\"></i> Quản lý liên hệ</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- /. NAV SIDE  -->");
      out.write("<div id=\"page-wrapper\">\r\n");
      out.write("    <div id=\"page-inner\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <h2>Quản lý bài hát</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /. ROW  -->\r\n");
      out.write("        <hr />\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <!-- Advanced Tables -->\r\n");
      out.write("                <div class=\"panel panel-default\">\r\n");
      out.write("                    <div class=\"panel-body\">\r\n");
      out.write("                        <div class=\"table-responsive\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-sm-6\">\r\n");
      out.write("                                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/songs/add\" class=\"btn btn-success btn-md\">Thêm</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-sm-6\" style=\"text-align: right;\">\r\n");
      out.write("                                    <form method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/admin/search\">\r\n");
      out.write("                                        <input type=\"submit\" name=\"submit\" value=\"Tìm kiếm\" class=\"btn btn-warning btn-sm\" style=\"float:right\" />\r\n");
      out.write("                                       ");

                                       String nameSearch = request.getParameter("search");
                                       
      out.write("<input type=\"search\" name=\"search\" value=\"");
if(nameSearch != null) out.print(nameSearch); 
      out.write("\" class=\"form-control input-sm\" placeholder=\"Nhập tên bài hát\" style=\"float:right; width: 300px;\" />\r\n");
      out.write("                                        <div style=\"clear:both\"></div>\r\n");
      out.write("                                    </form><br />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");

                            String error = request.getParameter("error");
                            if("1".equals(error)){
                            	out.print("<p style=\"color: red;\">ID không tồn tại.</p>");
                            }
                            if("2".equals(error)){
                            	out.print("<p style=\"color: red;\">Có lỗi khi xóa.</p>");
                            }
							if(request.getParameter("mes") != null){
								int mes = Integer.parseInt(request.getParameter("mes"));
								if(mes == 1){
									out.print("<p style=\"color: green;\">Thêm bài hát thành công.</p>");							
								}
								if(mes == 2){
									out.print("<p style=\"color: green;\">Sửa bài hát thành công.</p>");
								}
								if(mes == 3){
									out.print("<p style=\"color: green;\">Xóa bài hát thành công.</p>");
								}
							}
						
      out.write("<table class=\"table table-striped table-bordered table-hover\" id=\"dataTables-example\">\r\n");
      out.write("                                <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th>ID</th>\r\n");
      out.write("                                        <th>Tên bài hát</th>\r\n");
      out.write("                                        <th>Thể loại nhạc</th>\r\n");
      out.write("                                        <th>Lượt đọc</th>\r\n");
      out.write("                                        <th>Hình ảnh</th>\r\n");
      out.write("                                        <th width=\"160px\">Chức năng</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                ");

                                	CatergoriesDAO catDao = new CatergoriesDAO();
                                	ArrayList<Categories> listCat = catDao.getItems();
                                	ArrayList<Songs> listSong = (ArrayList) request.getAttribute("list");
                                	if(listSong != null && listSong.size() > 0){
                                		for(Songs objSong : listSong){                       		
                                		
      out.write("<tr>\r\n");
      out.write("	                                        <td>");
      out.print(objSong.getIdSong() );
      out.write("</td>\r\n");
      out.write("	                                        <td class=\"center\">");
      out.print(objSong.getSongName() );
      out.write("</td>\r\n");
      out.write("	                                        ");

	                                        	String name = "";
	                                        	for(Categories objCat : listCat){
	                                        		if(objSong.getId_cat() == objCat.getIdCat()){
	                                        			name = objCat.getCatName();
	                                        			 } }
      out.write("<td class=\"center\">");
      out.print(name);
      out.write("</td>\r\n");
      out.write("	                                        \r\n");
      out.write("	                                        \r\n");
      out.write("	                                        <td class=\"center\">");
      out.print(objSong.getCounter() );
      out.write("</td>\r\n");
      out.write("	                                        <td class=\"center\">\r\n");
      out.write("												<img width=\"200px\" height=\"200px\" src=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/admin/assets/img/");
      out.print(objSong.getPicture());
      out.write("\" alt=\"");
      out.print(objSong.getSongName());
      out.write("\"/>\r\n");
      out.write("	                                        </td>\r\n");
      out.write("	                                        ");
if("admin".equals(userLogin.getUsername())){ 
      out.write("<td class=\"center\">\r\n");
      out.write("	                                            <a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/songs/edit-song?sid=");
      out.print(objSong.getIdSong());
      out.write("\" title=\"\" class=\"btn btn-primary\"><i class=\"fa fa-edit \"></i> Sửa</a>\r\n");
      out.write("	                                            <a href=\"#\" onclick=\"showMess(");
      out.print(objSong.getIdSong());
      out.write(")\" title=\"\" class=\"btn btn-danger\"><i class=\"fa fa-pencil\"></i> Xóa</a>\r\n");
      out.write("	                                        </td>\r\n");
      out.write("	                                        ");
} 
      out.write("</tr>\r\n");
      out.write("                                		");
 }  } 
      out.write("</tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                            ");

                            int endPage = (Integer)request.getAttribute("endPage");
                       		int index = (Integer)request.getAttribute("index");
                       		int total = (Integer)request.getAttribute("total");
                       		int num = 0;
                       		if(index<endPage){
                       			num = (index-1)*DefineUtil.NUMBER_PER_PAGE+DefineUtil.NUMBER_PER_PAGE;
                       		}else{
                       			num = total;
                       		}
                       		if(listSong != null || listSong.size() > 0){
                            
      out.write("<div class=\"row\">\r\n");
      out.write("                                <div class=\"col-sm-6\">\r\n");
      out.write("                                    <div class=\"dataTables_info\" id=\"dataTables-example_info\" style=\"margin-top:27px\">Hiển thị từ ");
      out.print((index-1)*DefineUtil.NUMBER_PER_PAGE+1);
      out.write(" đến ");
      out.print(num);
      out.write(" của ");
      out.print(total);
      out.write(" bài hát</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-sm-6\" style=\"text-align: right;\">\r\n");
      out.write("                                    <div class=\"dataTables_paginate paging_simple_numbers\" id=\"dataTables-example_paginate\">\r\n");
      out.write("                                        <ul class=\"pagination\">\r\n");
      out.write("                                        ");

                                        	if(index > 1){ 
      out.write("<li class=\"paginate_button previous\" aria-controls=\"dataTables-example\" tabindex=\"0\" id=\"dataTables-example_previous\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/songs?index=");
      out.print(index-1);
      out.write("\">Trang trước</a></li>                                        		\r\n");
      out.write("                                        	");
}
                                        
	
                                           for(int i = 1; i <= endPage; i++){
                                           
      out.write("<li class=\"paginate_button ");
      out.print(index==i ? "active" : "");
      out.write("\" aria-controls=\"dataTables-example\" tabindex=\"0\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/songs?index=");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a></li>\r\n");
      out.write("											");
} 

											if(index < endPage){ 
      out.write("<li class=\"paginate_button next\" aria-controls=\"dataTables-example\" tabindex=\"0\" id=\"dataTables-example_next\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/songs?index=");
      out.print(index+1);
      out.write("\">Trang tiếp</a></li>	\r\n");
      out.write("											");
}
      out.write("</ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
} 
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--End Advanced Tables -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("	function showMess(id) {\r\n");
      out.write("		var option = confirm(\"Bạn có chắc chắn muốn xóa không\");\r\n");
      out.write("		if(option){\r\n");
      out.write("			location.href = \"");
      out.print(request.getContextPath());
      out.write("/admin/songs/del?dsid=\"+id;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("    document.getElementById(\"song\").classList.add('active-menu');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- /. PAGE INNER  -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /. WRAPPER  -->\r\n");
      out.write("<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->\r\n");
      out.write("<!-- JQUERY -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/ckeditor/ckeditor.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/admin/assets/js/jquery-3.2.1.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/admin/assets/js/jquery.validate.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/admin/assets/js/validate_admin.js\"></script>\r\n");
      out.write("<!-- BOOTSTRAP SCRIPTS -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/admin/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- METISMENU SCRIPTS -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/admin/assets/js/jquery.metisMenu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- CUSTOM SCRIPTS -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/GiaoDien/admin/assets/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
